name: Terraform-Init
description: A GitHub Action to run 'terraform init' in a specified directory.
author: TFActions
branding:
  icon: upload-cloud
  color: white

inputs:
  Lock:
    description: Whether to lock the state file when running 'terraform init'. Accepts 'true' or 'false'.
    required: false
    default: 'false'
  Debug:
    description: Enable debug output.
    required: false
    default: 'false'
  Verbose:
    description: Enable verbose output.
    required: false
    default: 'false'
  Version:
    description: Specifies the version of the GitHub module to be installed. The value must be an exact version.
    required: false
  Prerelease:
    description: Allow prerelease versions if available.
    required: false
    default: 'false'
  WorkingDirectory:
    description: The working directory where the script will run from.
    required: false
    default: ${{ github.workspace }}

runs:
  using: composite
  steps:
    - name: Terraform-Init
      uses: PSModule/GitHub-Script@v1
      env:
        PSMODULE_TEMPLATE_ACTION_INPUT_Lock: ${{ inputs.Lock }}
      with:
        Name: Terraform-Init
        Debug: ${{ inputs.Debug }}
        Prerelease: ${{ inputs.Prerelease }}
        Verbose: ${{ inputs.Verbose }}
        Version: ${{ inputs.Version }}
        WorkingDirectory: ${{ inputs.WorkingDirectory }}
        Script: ${{ github.action_path }}/scripts/main.ps1
